# Generated by Django 4.2.2 on 2023-07-03 00:20

import account.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(validators=[account.validators.validate_adult]),
        ),
    ]
