# Generated by Django 4.2.2 on 2023-07-03 00:20

from django.db import migrations, models
import hotel.validators


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='features',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[hotel.validators.validate_positive]),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[hotel.validators.validate_positive]),
        ),
    ]
